models:
  - pyfile: '2021_IJCAI'
    wander_mean_speed: '0.09' # m/s, from input file
    homing_mean_speed: '0.08' # m/s, from input file
  # - pyfile: 'homing_time'
  # - pyfile: 'perf_measures'
  # - pyfile: 'blocks'
  # - pyfile: 'interference'
