# Intra-scenario
intra_scenario:
  graphs:
    # raw performance
    - src_stem: PM-blocks-transported-cum-avg
      dest_stem: cc-PM-blocks-transported-cum-avg
      title: 'Swarm Performance'
      label: 'Total Blocks Collected'

    # scalability
    - src_stem: PM-scalability-norm
      dest_stem: cc-PM-scalability-norm
      title: 'Swarm Scalability (Normalized)'
      label: 'Scalability Value'

    - src_stem: PM-scalability-parallel-frac
      dest_stem: cc-PM-scalability-parallel-frac
      title: 'Swarm Scalability (Parallel Fraction)'
      label: 'Scalability Value'

      # self-organization
    - src_stem: PM-self-org-ifl
      dest_stem: cc-PM-self-org-ifl
      title: 'Swarm Spatial Self Organization'
      label: 'Self-Organization Value'

    - src_stem: PM-self-org-mpg
      dest_stem: cc-PM-self-org-mpg
      title: 'Swarm Task-Based Self-Organization'
      label: 'Self-Organization Value'

      # flexibility
    - src_stem: PM-reactivity
      dest_stem: cc-PM-reactivity
      title: 'Swarm Reactivity'
      label: 'Reactivity Value'

    - src_stem: PM-adaptability
      dest_stem: cc-PM-adaptability
      title: 'Swarm Adaptability'
      label: 'Adaptability Value'

    - src_stem: PM-robustness-pd
      dest_stem: cc-PM-robustness-pd
      title: 'Swarm Robustness (Population Dynamics)'
      label: 'Robustness Value'

    # robustness
    - src_stem: PM-robustness-saa
      dest_stem: cc-PM-robustness-saa
      title: 'Swarm Robustness (SAA Noise)'
      label: 'Robustness Value'

# Inter-scenario
inter_scenario:
  graphs:
    # raw performance
    - src_stem: PM-raw
      dest_stem: sc-PM-raw
      title: 'Swarm Performance'
      label: 'Block Collection Rate'

      # scalability
    - src_stem: PM-scalability-parallel-frac
      dest_stem: sc-PM-scalability-parallel-frac
      title: 'Swarm Scalability (Parallel Fraction)'
      label: 'Scalability Value'

      # self-organization
    - src_stem: PM-self-org-mfl
      dest_stem: sc-PM-self-org-mfl
      title: 'Swarm Spatial Self Organization'
      label: 'Self-Organization Value'
